In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [4]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype


dtype('float64')

In [5]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
np.shape(arr3)

(3, 3)

In [7]:
import numpy as np
import pandas as pd

df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [8]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [9]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]])

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [10]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [11]:
np.random.randint(0, 4, (3, 3))

array([[2, 1, 3],
       [1, 2, 2],
       [3, 0, 1]])

In [12]:
np.random.randint(0, 5, (3, 3))

array([[0, 4, 3],
       [4, 4, 0],
       [1, 2, 0]])

In [13]:
np.random.randint(0, 5, 3)

array([1, 4, 2])

In [14]:
np.random.randint(0, 6, (3, 3))

array([[2, 2, 3],
       [4, 5, 5],
       [5, 2, 3]])

In [16]:
my_array = np.array([x for x in range(10)])

In [17]:
my_array[5]

5

In [18]:
my_array[-1]

9

In [19]:
my_array[3:6]

array([3, 4, 5])

In [20]:
my_array[1:8:3]


array([1, 4, 7])

In [21]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

In [22]:
my_array[1][2]

12

In [23]:
my_array[1,2]

12

In [24]:
my_array[1]

array([10, 11, 12, 13])

In [25]:
my_array[:,2]

array([ 3, 12, 47])

In [26]:
my_array[1:, 1:3]

array([[11, 12],
       [46, 47]])

In [27]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [28]:
my_array = np.random.randint(1, 100, (4, 6))

In [29]:
my_array

array([[71, 97, 16, 92, 29, 91],
       [84, 53, 29, 42, 44, 67],
       [29,  4, 57, 64, 27,  4],
       [41, 43, 64, 74, 16, 35]])

In [30]:
my_slice = my_array[1:3, 2:4]

In [31]:
my_slice

array([[29, 42],
       [57, 64]])

In [34]:
my_slice[:] = 0

In [35]:
my_array

array([[71, 97, 16, 92, 29, 91],
       [84, 53,  0,  0, 44, 67],
       [29,  4,  0,  0, 27,  4],
       [41, 43, 64, 74, 16, 35]])

In [38]:
a = np.array([3,6,9])
b = np.array([12,15,18])

In [40]:
result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [41]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [42]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[1, 1, 4, 6, 5],
       [9, 5, 6, 3, 7],
       [4, 9, 7, 2, 8],
       [2, 9, 5, 4, 5]])

In [43]:
my_array

array([1, 1, 4, 6, 5, 9, 5, 6, 3, 7, 4, 9, 7, 2, 8, 2, 9, 5, 4, 5])

In [44]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])

In [45]:
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [46]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [47]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[4, 9, 0, 1],
       [6, 7, 2, 0],
       [0, 6, 9, 8]])

In [48]:
my_array<5

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [ True, False, False, False]])

In [49]:
my_array[my_array<5]

array([4, 0, 1, 2, 0, 0])

In [50]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[4, 0],
       [6, 2],
       [0, 9]])

In [51]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[4, 4, 0, 3, 4, 5],
       [2, 0, 3, 1, 3, 7],
       [1, 3, 9, 4, 8, 8],
       [1, 5, 7, 2, 7, 7]])

In [52]:
np.sort(my_array, axis=1)

array([[0, 3, 4, 4, 4, 5],
       [0, 1, 2, 3, 3, 7],
       [1, 3, 4, 8, 8, 9],
       [1, 2, 5, 7, 7, 7]])

In [53]:
np.sort(my_array, axis=0)

array([[1, 0, 0, 1, 3, 5],
       [1, 3, 3, 2, 4, 7],
       [2, 4, 7, 3, 7, 7],
       [4, 5, 9, 4, 8, 8]])

In [54]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [55]:
mean = np.mean(students[:,-1])
mean

NameError: name 'students' is not defined